<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Combat\Terraria.Combat.csproj" />
    <ProjectReference Include="..\Content\Terraria.Content.csproj" />
    <ProjectReference Include="..\Relationships\Terraria.Relationships.csproj" />
    <ProjectReference Include="..\SpatialSimulation\Terraria.SpatialSimulation.csproj" />
  </ItemGroup>
</Project>
