using Terraria.Dome.Simulation.Components;

using EntityEcs.Components;
namespace Terraria.Dome.Simulation.Projectile.Definitions;

public readonly record struct ProjectileDefinition(
  int ProjectileType,
  int BehaviorId,
  int Damage,
  int LifetimeTicks,
  ColliderComponent Collider,
  bool Friendly,
  bool Hostile,
  int MaximumPenetration,
  int MaximumBounces = 0,
  ProjectileLiquidPolicy LiquidPolicy = ProjectileLiquidPolicy.Pass,
  PlayerDamagePolicy PlayerDamagePolicy = PlayerDamagePolicy.None,
  float Knockback = 0.0f,
  int OriginalDamage = 0,
  bool CollidesWithTiles = true,
  ProjectileOnDespawnAreaDamage OnDespawnAreaDamage = default,
  ProjectileOnDespawnStatusEffect OnDespawnStatusEffect = default,
  ProjectileOnHitStatusEffect OnHitStatusEffect = default,
  bool ReflectsFromTiles = false,
  ProjectileChildSpawn ChildSpawn = default,
  float BounceVelocityMultiplier = 1.0f,
  float MinimumBounceSpeed = 0.0f,
  int ExtraUpdates = 0,
  bool IgnoreWater = false,
  bool CorrectSlopeCollision = true,
  bool UsesStaticNpcImmunity = false,
  int StaticNpcHitCooldownTicks = -1,
  bool AppliesImmunityTimeOnSingleHits = false,
  ProjectileDamageClass DamageClass = ProjectileDamageClass.Generic,
  int LegacyAiStyle = 0,
  bool IsColdDamage = false,
  bool IsArrow = false,
  int ArmorPenetration = 0,
  int BonusCritChance = 0,
  int BonusTagDamage = 0,
  int TagEffectType = 0,
  bool StopsDealingDamageAfterPenetrateHits = false,
  bool NoEnchantments = false,
  bool NoEnchantmentVisuals = false,
  bool OriginatedFromActivableTile = false,
  bool NoDropItem = false,
  bool UsesLocalNpcImmunity = false,
  int LocalNpcHitCooldownTicks = -2,
  bool IsNetworkImportant = false,
  float Scale = 1.0f,
  bool OwnerHitCheck = false,
  float OwnerHitCheckDistance = 1000.0f,
  bool IsSentry = false,
  bool IsMinion = false,
  float MinionSlots = 0.0f,
  int MinionPosition = 0,
  bool IsTrap = false,
  bool IsBobber = false,
  bool IsCounterweight = false,
  ProjectileHostileDamageScaling HostileDamageScaling = ProjectileHostileDamageScaling.Default,
  bool DecidesManualFallThrough = false,
  bool ManualDirectionChange = false,
  bool UsesOwnerMeleeHitCooldown = false,
  bool CopiesOwnerAttackCooldownToLocalImmunityOnSpawn = false);
