<Project>
  <PropertyGroup>
    <TargetFramework Condition="'$(TargetFramework)' == ''">net10.0</TargetFramework>
    <RepositoryBuildRoot>$(MSBuildThisFileDirectory)Build\</RepositoryBuildRoot>
    <BaseOutputPath>$(RepositoryBuildRoot)bin\$(MSBuildProjectName)\</BaseOutputPath>
    <BaseIntermediateOutputPath>$(RepositoryBuildRoot)obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
    <RestorePackagesPath>$(RepositoryBuildRoot)packages\</RestorePackagesPath>
    <LangVersion>preview</LangVersion>
    <DefaultItemExcludes>$(DefaultItemExcludes);Build\**\*</DefaultItemExcludes>
    <AppendTargetFrameworkToOutputPath>true</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>true</AppendRuntimeIdentifierToOutputPath>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
  </PropertyGroup>
  <PropertyGroup Condition="'$(FixtureHostBuild)' == 'true'">
    <BaseOutputPath>$(RepositoryBuildRoot)bin\FixtureHost\$(MSBuildProjectName)\</BaseOutputPath>
    <BaseIntermediateOutputPath>$(RepositoryBuildRoot)obj\FixtureHost\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
  </PropertyGroup>
</Project>
