<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Terraria.Arch.Verification</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Arch" Version="2.1.0" />
  </ItemGroup>
</Project>
