namespace Terraria.Dome.Protocol.V1456.Compatibility;

public readonly record struct LegacyTileSquareTile(
  bool IsActive,
  bool HasWall,
  bool HasLiquid,
  bool HasWire,
  bool IsHalfBrick,
  bool HasActuator,
  bool IsInactive,
  bool HasWire2,
  bool HasWire3,
  byte TileColor,
  byte WallColor,
  byte Slope,
  bool HasWire4,
  bool IsFullBrightBlock,
  bool IsFullBrightWall,
  bool IsInvisibleBlock,
  bool IsInvisibleWall,
  ushort TileType,
  bool IsFrameImportant,
  short FrameX,
  short FrameY,
  ushort WallType,
  byte LiquidAmount,
  byte LiquidType);
