<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Physics\Terraria.Physics.csproj" />
    <ProjectReference Include="..\Share\Entity\Terraria.EntityEcs.csproj" />
  </ItemGroup>
</Project>
