namespace Terraria.Player;

[Flags]
public enum PlayerLifeRegenStatusFlags : ulong
{
  None = 0,
  ShinyStone = 1UL << 0,
  StandingStill = 1UL << 1,
  ItemAnimating = 1UL << 2,
  Poisoned = 1UL << 3,
  Venom = 1UL << 4,
  OnFire = 1UL << 5,
  OnFire3 = 1UL << 6,
  OnFrostBurn = 1UL << 7,
  OnFrostBurn2 = 1UL << 8,
  OnFire2 = 1UL << 9,
  Burned = 1UL << 10,
  Suffocating = 1UL << 11,
  Electrified = 1UL << 12,
  ControlLeft = 1UL << 13,
  ControlRight = 1UL << 14,
  Tongued = 1UL << 15,
  ExpertMode = 1UL << 16,
  Honey = 1UL << 17,
  NebulaLevelLife = 1UL << 18,
  UsedAegisCrystal = 1UL << 19,
  CrimsonRegen = 1UL << 20,
  Starving = 1UL << 21,
  HeartyMeal = 1UL << 22,
  Bleed = 1UL << 23,
  PalladiumRegen = 1UL << 24,
  VampireSeed = 1UL << 25,
  DrippingSlime = 1UL << 26,
  Resting = 1UL << 27,
  Moving = 1UL << 28,
  Grappling = 1UL << 29,
  WellFed = 1UL << 30,
  Rabid = 1UL << 31,
  StarvingHarshBiome = 1UL << 32,
}
