using Terraria.Dome.Simulation.Items;
using Terraria.Dome.Simulation.Player.Components;

namespace Terraria.Dome.Simulation;

public readonly record struct PlayerSnapshot(
  PlayerHandle Player,
  SimulationVector Position,
  SimulationVector Velocity,
  int Facing,
  bool IsGrounded,
  int Health,
  bool IsActive,
  int RespawnTicks,
  string AccountUuid = "",
  byte AssignedSlot = 0,
  int Mana = 0,
  int MaximumMana = 0,
  float GravityDirection = 1.0f,
  float ColliderWidth = 1.0f,
  float ColliderHeight = 2.0f,
  int MaximumHealth = 100,
  int Defense = 0,
  byte SelectedLoadout = 0,
  ushort AccessoryVisibility = 0,
  int EquipmentStateCount = 0,
  long EquipmentRevision = 0,
  int EquipmentLoadoutRevision = 0,
  int WellFedRank = 0,
  int WellFedTimeLeft = 0,
  int BuffCount = 0,
  long BuffRevision = 0,
  int SelectedSlot = 0,
  bool IsUsingItem = false,
  int ItemUseRevision = 0,
  int ItemUseCooldownTicks = 0,
  int ItemAnimationTicks = 0,
  bool IsChannelingItem = false,
  int LifeRegenUnitsPerTick = 60,
  int HealthRegenerationDelayTicks = 2,
  int HealthRegenerationAccumulator = 0,
  int ManaRegenerationDelayTicks = 0,
  int ManaRegenerationAccumulator = 0,
  int ImmunityRemainingTicks = 0,
  bool IsImmune = false,
  int FireCooldownTicks = 0,
  int Aggro = 0,
  int NoAggroNpcTypeCount = 0,
  bool HasInteractionTarget = false,
  PlayerInteractionMode InteractionMode = PlayerInteractionMode.None,
  ushort? MountType = null,
  bool Down = false,
  bool Up = false,
  bool Fire = false,
  bool UseTile = false,
  bool Dash = false,
  bool MoveLeft = false,
  bool MoveRight = false,
  bool Jump = false,
  bool UseItem = false,
  float Stealth = 1.0f,
  bool IsInvisible = false,
  bool HasShroomiteStealth = false,
  bool IsVortexStealthActive = false,
  int StealthTimer = 0,
  bool ItemAnimationJustStarted = false,
  int FlightTimeRemaining = 0,
  int FatigueRemaining = 0,
  bool IsSleeping = false,
  int TimeSleeping = 0,
  PlayerSleepWakeReason SleepWakeReason = PlayerSleepWakeReason.None,
  int PotionDelayTicks = 0,
  bool IsDead = false,
  int DeadTime = 0,
  int SpawnX = -1,
  int SpawnY = -1,
  int FishingSkill = 0,
  int GolferScoreAccumulated = 0,
  float Luck = 0.0f,
  byte LuckPotion = 0,
  bool DefendedByPaladin = false,
  bool HasPaladinShield = false,
  sbyte Shield = -1,
  bool ShieldRaised = false,
  int ShieldParryTimeLeft = 0,
  int Breath = 200,
  int BreathMax = 200,
  int LavaTime = 0,
  int LavaMax = 0,
  int Wings = 0,
  int WingsLogic = 0,
  float WingTime = 0.0f,
  int WingTimeMax = 0,
  int ShadowDodgeTimer = 0,
  int AttackTicks = 0,
  int ItemAnimation = 0,
  int ItemAnimationMax = 0,
  int ItemTime = 0,
  int ItemTimeMax = 0,
  int ToolTime = 0,
  bool MeleeScaleGlove = false,
  bool VoidVaultEnabled = false,
  bool ShadowDodge = false,
  float ShadowDodgeCharges = 0.0f,
  int BuffImmunityCount = 0,
  long EquipmentInventoryRevision = 0,
  ItemStack TrashItem = default);
