using System;
using Terraria.Dome.Simulation.Projectile.Definitions;
using Terraria.Dome.Simulation.WorldModel;

namespace Terraria.Dome.Simulation;

public readonly record struct ProjectileReplicationSnapshot(
  int ReplicationId,
  int ProjectileType,
  PlayerHandle Owner,
  SimulationVector Position,
  SimulationVector Velocity,
  int Damage,
  int RemainingLifetime,
  bool IsActive,
  long Revision,
  WorldSectionCoordinates Section,
  int Identity = 0,
  Guid? ProjectileUuid = null,
  float Ai0 = 0.0f,
  float Ai1 = 0.0f,
  float Ai2 = 0.0f,
  ushort Banner = 0,
  float Knockback = 0.0f,
  int OriginalDamage = 0,
  short Uuid = 0,
  ProjectileTombstoneReason TombstoneReason = ProjectileTombstoneReason.None,
  long TombstoneRetainedUntilTick = 0,
  float DefinitionKnockback = 0.0f,
  int DefinitionOriginalDamage = 0,
  bool Reflected = false,
  int LegacyAiStyle = 0,
  ProjectileDamageClass DamageClass = ProjectileDamageClass.Generic,
  bool IsColdDamage = false,
  bool IsArrow = false,
  int HitCount = 0,
  int UpdateCount = 0,
  int ArmorPenetration = 0,
  int BonusCritChance = 0,
  int BonusTagDamage = 0,
  int TagEffectType = 0,
  bool StopsDealingDamageAfterPenetrateHits = false,
  bool NoEnchantments = false,
  bool NoEnchantmentVisuals = false,
  bool OriginatedFromActivableTile = false,
  bool NoDropItem = false,
  bool UsesLocalNpcImmunity = false,
  int LocalNpcHitCooldownTicks = 1,
  bool IsNetworkImportant = false,
  float Scale = 1.0f,
  bool OwnerHitCheck = false,
  float OwnerHitCheckDistance = 1000.0f,
  bool IsSentry = false,
  bool IsMinion = false,
  float MinionSlots = 0.0f,
  int MinionPosition = 0,
  bool IsTrap = false,
  bool IsBobber = false,
  bool IsCounterweight = false,
  int MaximumPenetration = 1,
  bool DecidesManualFallThrough = false,
  bool ShouldFallThrough = false,
  int Direction = 1,
  bool ManualDirectionChange = false,
  bool UsesOwnerMeleeHitCooldown = false,
  ProjectileHostileDamageScaling HostileDamageScaling = ProjectileHostileDamageScaling.Default,
  bool CollidesWithTiles = true,
  bool IgnoreWater = false,
  bool ReflectsFromTiles = false,
  bool CorrectSlopeCollision = true,
  int MaximumBounces = 0,
  float BounceVelocityMultiplier = 1.0f,
  float MinimumBounceSpeed = 0.0f,
  ProjectileLiquidPolicy LiquidPolicy = ProjectileLiquidPolicy.Pass,
  ProjectileChildSpawn ChildSpawn = default,
  ProjectileOnHitStatusEffect OnHitStatusEffect = default,
  ProjectileOnDespawnStatusEffect OnDespawnStatusEffect = default,
  ProjectileOnDespawnAreaDamage OnDespawnAreaDamage = default,
  int BehaviorId = 0,
  bool Friendly = false,
  bool Hostile = false,
  PlayerDamagePolicy PlayerDamagePolicy = PlayerDamagePolicy.None,
  ushort MinionSpawnItemType = 0,
  int MinionSpawnItemPrefix = 0,
  float LocalAi0 = 0.0f,
  float LocalAi1 = 0.0f,
  float LocalAi2 = 0.0f,
  bool SecondaryUpdatePending = false,
  int NetSpam = 0,
  int SoundDelay = 0,
  bool TileCollisionEnabled = true,
  bool PrimaryUpdatePending = false,
  bool IsDd2Summon = false,
  bool CopiesOwnerAttackCooldownToLocalImmunityOnSpawn = false,
  bool NetworkUpdateReady = true);
