namespace Terraria.Dome.Simulation.WorldGeneration;

public readonly record struct WorldGenerationProgressionState(
  bool Crimson,
  bool GeneratingRandomEvil,
  bool SpawnEye,
  bool SpawnHardBoss,
  bool SpawnMeteor,
  bool ShadowOrbSmashed,
  int ShadowOrbCount,
  int AltarCount,
  int MeteorShowerCount,
  int NpcSpawnDelay,
  int NpcSpawnPeriod,
  int PrioritizedTownNpcType,
  bool WorldIsInfected,
  bool WorldIsFrozen,
  bool StartInHardmode,
  bool WorldCleared,
  bool LoadFailed,
  bool IsTransforming,
  int ActiveTransformations,
  long GenerationId,
  long GenerationCursor,
  WorldGenerationStage Stage);
