namespace Terraria.Dome.Simulation.WorldGeneration;

public readonly record struct WorldGenerationHousingState(
  int RoomTiles,
  int MaxRoomTiles,
  int MaxRoomSize,
  int RoomX1,
  int RoomX2,
  int RoomY1,
  int RoomY2,
  int BestX,
  int BestY,
  int HighScore,
  bool CanSpawn,
  bool HouseTile,
  bool RoomTorch,
  bool RoomDoor,
  bool RoomChair,
  bool RoomTable,
  bool RoomHasStinkbug,
  bool RoomHasEchoStinkbug,
  bool CurrentlyTryingAlternateSpot,
  int SharedRoomX,
  (int X, int Y)? LastFoundHouse,
  string? FailureReason);
