using System;
using Terraria.WorldFile.V319.Model;

namespace Terraria.WorldCompatibility.Model;

public sealed record CompatibilityWorldMetadata(
  string Name,
  int WorldId,
  int Width,
  int Height,
  int SpawnX,
  int SpawnY,
  int LeftWorld = 0,
  int RightWorld = 0,
  int TopWorld = 0,
  int BottomWorld = 0,
  double? WorldSurface = null,
  byte MoonPhase = 0,
  bool IsBloodMoon = false,
  bool IsEclipse = false,
  bool IsCrimsonWorld = false,
  bool IsHardMode = false,
  bool DefeatedEyeOfCthulhu = false,
  bool DefeatedEaterOrBrain = false,
  bool DefeatedSkeletron = false,
  bool DefeatedMechanicalBoss = false,
  bool DefeatedPlantera = false,
  bool DefeatedGolem = false,
  int InvasionType = 0,
  int InvasionSize = 0,
  double InvasionX = 0,
  bool DefeatedGoblins = false,
  bool DefeatedFrost = false,
  bool DefeatedPirates = false,
  bool DefeatedMartians = false,
  int GameMode = 0,
  bool IsMeteorScheduled = false,
  float? WindSpeedTarget = null,
  bool? IsRaining = null,
  int? RainTimeTicks = null,
  float? MaximumRainStrength = null,
  bool? IsRemixWorld = null,
  double TimeOfDay = 0,
  bool IsDayTime = true,
  ulong? WorldGeneratorVersion = null,
  Guid? UniqueId = null,
  string? SeedText = null)
{
  public string Name { get; init; } = Name ?? throw new ArgumentNullException(nameof(Name));

  internal static CompatibilityWorldMetadata From(LegacyWorldMetadata metadata)
  {
    ArgumentNullException.ThrowIfNull(metadata);
    return new CompatibilityWorldMetadata(
      metadata.Name,
      metadata.WorldId,
      metadata.Width,
      metadata.Height,
      metadata.SpawnX,
      metadata.SpawnY,
      metadata.LeftWorld,
      metadata.RightWorld,
      metadata.TopWorld,
      metadata.BottomWorld,
      metadata.WorldSurface,
      metadata.MoonPhase,
      metadata.IsBloodMoon,
      metadata.IsEclipse,
      metadata.IsCrimsonWorld,
      metadata.IsHardMode,
      metadata.DefeatedEyeOfCthulhu,
      metadata.DefeatedEaterOrBrain,
      metadata.DefeatedSkeletron,
      metadata.DefeatedMechanicalBoss,
      metadata.DefeatedPlantera,
      metadata.DefeatedGolem,
      metadata.InvasionType,
      metadata.InvasionSize,
      metadata.InvasionX,
      metadata.DefeatedGoblins,
      metadata.DefeatedFrost,
      metadata.DefeatedPirates,
      metadata.DefeatedMartians,
      metadata.GameMode,
      metadata.IsMeteorScheduled,
      metadata.WindSpeedTarget,
      metadata.IsRaining,
      metadata.RainTimeTicks,
      metadata.MaximumRainStrength,
      metadata.IsRemixWorld,
      metadata.TimeOfDay,
      metadata.IsDayTime,
      metadata.WorldGeneratorVersion,
      metadata.UniqueId,
      metadata.SeedText);
  }
}
