using Terraria.Dome.Simulation;
using Terraria.Dome.Simulation.Player.Components;

namespace Terraria.Dome.Protocol.V1456.Isolation;

public readonly record struct NetworkPlayerSlice(
  byte PlayerSlot,
  bool IsActive,
  float PositionX,
  float PositionY,
  float VelocityX,
  float VelocityY,
  int Facing,
  int Health,
  int Mana,
  int MaximumMana,
  int RespawnTicks = 0,
  float GravityDirection = 1.0f,
  float ColliderWidth = 1.0f,
  float ColliderHeight = 2.0f,
  int SelectedSlot = 0,
  byte SelectedLoadout = 0,
  ushort AccessoryVisibility = 0,
  int EquipmentStateCount = 0,
  long EquipmentRevision = 0,
  int EquipmentLoadoutRevision = 0,
  int BuffCount = 0,
  long BuffRevision = 0,
  int WellFedRank = 0,
  int WellFedTimeLeft = 0,
  int MaximumHealth = 100,
  int Defense = 0,
  bool IsGrounded = false,
  int LifeRegenUnitsPerTick = 60,
  int HealthRegenerationDelayTicks = 2,
  int HealthRegenerationAccumulator = 0,
  int ManaRegenerationDelayTicks = 0,
  int ManaRegenerationAccumulator = 0,
  int ImmunityRemainingTicks = 0,
  bool IsImmune = false,
  bool IsUsingItem = false,
  bool UseItem = false,
  int ItemUseRevision = 0,
  int ItemUseCooldownTicks = 0,
  int ItemAnimationTicks = 0,
  bool IsChannelingItem = false,
  int FireCooldownTicks = 0,
  int Aggro = 0,
  int NoAggroNpcTypeCount = 0,
  bool HasInteractionTarget = false,
  PlayerInteractionMode InteractionMode = PlayerInteractionMode.None,
  bool Down = false,
  bool Up = false,
  bool Fire = false,
  bool UseTile = false,
  bool Dash = false,
  bool MoveLeft = false,
  bool MoveRight = false,
  bool Jump = false,
  float Stealth = 1.0f,
  bool IsInvisible = false,
  bool HasShroomiteStealth = false,
  bool IsVortexStealthActive = false,
  int StealthTimer = 0,
  bool ItemAnimationJustStarted = false)
{
  public static NetworkPlayerSlice From(PlayerSnapshot snapshot)
  {
    return new NetworkPlayerSlice(
      snapshot.AssignedSlot,
      snapshot.IsActive,
      snapshot.Position.X,
      snapshot.Position.Y,
      snapshot.Velocity.X,
      snapshot.Velocity.Y,
      snapshot.Facing,
      snapshot.Health,
      snapshot.Mana,
      snapshot.MaximumMana,
      snapshot.RespawnTicks,
      snapshot.GravityDirection,
      snapshot.ColliderWidth,
      snapshot.ColliderHeight,
      snapshot.SelectedSlot,
      snapshot.SelectedLoadout,
      snapshot.AccessoryVisibility,
      snapshot.EquipmentStateCount,
      snapshot.EquipmentRevision,
      snapshot.EquipmentLoadoutRevision,
      snapshot.BuffCount,
      snapshot.BuffRevision,
      snapshot.WellFedRank,
      snapshot.WellFedTimeLeft,
      snapshot.MaximumHealth,
      snapshot.Defense,
      snapshot.IsGrounded,
      snapshot.LifeRegenUnitsPerTick,
      snapshot.HealthRegenerationDelayTicks,
      snapshot.HealthRegenerationAccumulator,
      snapshot.ManaRegenerationDelayTicks,
      snapshot.ManaRegenerationAccumulator,
      snapshot.ImmunityRemainingTicks,
      snapshot.IsImmune,
      snapshot.IsUsingItem,
      snapshot.UseItem,
      snapshot.ItemUseRevision,
      snapshot.ItemUseCooldownTicks,
      snapshot.ItemAnimationTicks,
      snapshot.IsChannelingItem,
      snapshot.FireCooldownTicks,
      snapshot.Aggro,
      snapshot.NoAggroNpcTypeCount,
      snapshot.HasInteractionTarget,
      snapshot.InteractionMode,
      snapshot.Down,
      snapshot.Up,
      snapshot.Fire,
      snapshot.UseTile,
      snapshot.Dash,
      snapshot.MoveLeft,
      snapshot.MoveRight,
      snapshot.Jump,
      snapshot.Stealth,
      snapshot.IsInvisible,
      snapshot.HasShroomiteStealth,
      snapshot.IsVortexStealthActive,
      snapshot.StealthTimer,
      snapshot.ItemAnimationJustStarted);
  }
}
