namespace Terraria.Dome.Simulation.WorldModel;

public readonly record struct WorldTile(
  bool IsActive,
  ushort Type,
  byte LiquidAmount = 0,
  byte LiquidType = 0,
  short FrameX = 0,
  short FrameY = 0,
  ushort WallType = 0,
  bool HasWire = false,
  bool HasWire2 = false,
  bool HasWire3 = false,
  bool HasWire4 = false,
  bool IsHalfBrick = false,
  byte Slope = 0,
  bool IsActuated = false,
  bool IsInactive = false,
  byte TileColor = 0,
  byte WallColor = 0,
  bool IsInvisibleBlock = false,
  bool IsInvisibleWall = false,
  bool IsFullbrightBlock = false,
  bool IsFullbrightWall = false,
  byte WallFrameNumber = 0,
  short WallFrameX = 0,
  short WallFrameY = 0);
