namespace Terraria.WorldCompatibility.Model;

public readonly record struct CompatibilityTile(
  int X,
  int Y,
  bool IsActive,
  ushort TileType,
  ushort WallType = 0,
  byte LiquidAmount = 0,
  byte LiquidKind = 0,
  bool HasWire = false,
  bool HasWire2 = false,
  bool HasWire3 = false,
  bool HasWire4 = false,
  bool IsHalfBrick = false,
  byte Slope = 0,
  bool IsActuated = false,
  bool IsInactive = false,
  short FrameX = 0,
  short FrameY = 0,
  byte TileColor = 0,
  byte WallColor = 0,
  bool IsInvisibleBlock = false,
  bool IsInvisibleWall = false,
  bool IsFullbrightBlock = false,
  bool IsFullbrightWall = false);
