namespace Terraria.Dome.Protocol.V1456.Protocol;

public enum TerrariaMessageId : byte
{
  Hello = 1,
  SetUserSlot = 3,
  SyncPlayer = 4,
  SyncEquipment = 5,
  RequestWorldData = 6,
  WorldData = 7,
  SpawnTileData = 8,
  StatusTextSize = 9,
  TileSection = 10,
  PlayerSpawn = 12,
  PlayerControls = 13,
  PlayerActive = 14,
  PlayerLifeMana = 16,
  TileManipulation = 17,
  SetTime = 18,
  ToggleDoorState = 19,
  TileSquare = 20,
  OpenSignRequest = 46,
  OpenSignResponse = 47,
  RequestChestOpen = 31,
  SyncChestItem = 32,
  SyncPlayerChest = 34,
  SyncPlayerZone = 36,
  SyncTalkNpc = 40,
  SyncItem = 21,
  SyncNPC = 23,
  SyncProjectile = 27,
  KillProjectile = 29,
  ItemRotationAndAnimation = 42,
  InitialSpawn = 49,
  PlayerBuffs = 50,
  UniqueTownNpcInfoSyncRequest = 56,
  NpcBuffs = 54,
  WorldBiomeTypes = 57,
  NpcHome = 60,
  PlayerUuid = 68,
  ChestName = 69,
  AnglerQuest = 74,
  NetModules = 82,
  TowerShieldStrengths = 101,
  FinishedConnectingToServer = 129,
  CavernMonsterTypes = 136,
  HostStatus = 139,
  ClientSyncedInventory = 138,
  SyncLoadout = 147,
  Ping = 154,
  SyncChestSize = 155,
  RequestSection = 159
}
