using System;

namespace Terraria.WorldFile.V319.Model;

public sealed record LegacyWorldMetadata(
  string Name,
  int WorldId,
  int Width,
  int Height,
  int SpawnX,
  int SpawnY,
  int LeftWorld = 0,
  int RightWorld = 0,
  int TopWorld = 0,
  int BottomWorld = 0,
  double WorldSurface = 0,
  double RockLayer = 0,
  byte MoonPhase = 0,
  bool IsBloodMoon = false,
  bool IsEclipse = false,
  bool IsCrimsonWorld = false,
  bool IsHardMode = false,
  bool DefeatedEyeOfCthulhu = false,
  bool DefeatedEaterOrBrain = false,
  bool DefeatedSkeletron = false,
  bool DefeatedMechanicalBoss = false,
  bool DefeatedPlantera = false,
  bool DefeatedGolem = false,
  int InvasionType = 0,
  int InvasionSize = 0,
  double InvasionX = 0,
  bool DefeatedGoblins = false,
  bool DefeatedFrost = false,
  bool DefeatedPirates = false,
  bool DefeatedMartians = false,
  int GameMode = 0,
  bool IsMeteorScheduled = false,
  float? WindSpeedTarget = null,
  bool? IsRaining = null,
  int? RainTimeTicks = null,
  float? MaximumRainStrength = null,
  bool? IsRemixWorld = null,
  double TimeOfDay = 0,
  bool IsDayTime = true,
  ulong? WorldGeneratorVersion = null,
  Guid? UniqueId = null,
  string? SeedText = null,
  bool? IsNoTrapsWorld = null,
  bool? IsSkyblockWorld = null,
  bool? IsGoodWorld = null)
{
  public string Name { get; init; } = Name ?? throw new ArgumentNullException(nameof(Name));
}
