<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Terraria.Dome.Protocol.V1456\Terraria.Dome.Protocol.V1456.csproj" />
    <ProjectReference Include="..\Terraria.Dome.Simulation\Terraria.Dome.Simulation.csproj" />
    <ProjectReference Include="..\Terraria.WorldCompatibility\Terraria.WorldCompatibility.csproj" />
    <ProjectReference Include="..\Terraria.WorldFile.V319\Terraria.WorldFile.V319.csproj" />
  </ItemGroup>
</Project>
