<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Arch" Version="2.1.0" />
    <ProjectReference Include="..\..\..\src\Share\Entity\Terraria.EntityEcs.csproj" />
  </ItemGroup>
</Project>
