namespace Terraria.Dome.Simulation.WorldGeneration;

public enum LegacyWorldInfectionConversionCategory
{
  Torch = 0,
  Moss = 1,
  Stone = 2,
  MossOrStone = 3,
  JungleGrass = 4,
  GolfGrass = 5,
  Grass = 6,
  Ice = 7,
  Sand = 8,
  HardenedSand = 9,
  Sandstone = 10,
  Thorn = 11,
  Dirt = 12,
  Snow = 13,
  NewWall1 = 14,
  NewWall2 = 15,
  NewWall3 = 16,
  NewWall4 = 17,
  AdjacentGrassCleanup = 18,
  MushroomGrass = 19,
  GlowingMushroomWall = 20,
  ChlorophyteMushroomSurface = 21,
  ChlorophyteGrass = 22,
  ChlorophyteSecondaryGrass = 23,
  ChlorophyteStone = 24,
  ChlorophyteSand = 25,
  ChlorophyteHardenedSand = 26,
  ChlorophyteSandstone = 27,
  ChlorophyteKill = 28,
  StoneFamilyWall = 29,
  HardenedSandDirtSnowWall = 30,
  GrassSandSnowDirt = 31,
  GrassSandHardenedSandSnowDirt = 32,
  MossStoneIceSandstone = 33
}
