using NSSLC.WorldGeneration.Geometry;
using NSSLC.WorldGeneration.ID;
namespace NSSLC.WorldGeneration;

/// <summary>Local generation state; reset and initialization are implemented in MainHost.</summary>
public static partial class Main
{
  public static dynamic ActivePlayerFileData;
  public static IO.WorldFileData ActiveWorldFileData;
  public static bool afterPartyOfDoom = default;
  public static int BartenderHelpTextIndex = default;
  public static dynamic BestiaryTracker;
  public static bool bloodMoon = default;
  public static float bottomWorld = default;
  public static int[] caveBackStyle = new int[4];
  public static int[] caveBackX = new int[4];
  public static NSSLC.WorldGeneration.Chest[] chest = System.Array.Empty<NSSLC.WorldGeneration.Chest>();
  public static bool clearMap = default;
  public static float cloudAlpha = default;
  public static float cloudBGActive = default;
  public static int coinRain = default;
  public static int[] corruptBG = new int[3];
  public static bool[] countsAsHostForGameplay = new bool[256];
  public static dynamic CreativeMenu;
  public static int[] crimsonBG = new int[3];
  public static dynamic CurrentFrameFlags;
  public static Vector2 CurrentPan = default;
  public static int dayRate = default;
  public static bool dayTime = default;
  public static bool dedServ = default;
  public static DataStructures.BackgroundVariantSet desertBackgroundSet = new();
  public static int desiredWorldTilesUpdateRate = default;
  public static float Difficulty = default;
  public static int DiscoB = default;
  public static int DiscoG = default;
  public static int DiscoR = default;
  public static bool dontStarveWorld = default;
  public static dynamic DroneCameraTracker;
  public static bool drunkWorld = default;
  public static bool dualDungeonsSeed = default;
  public static int dungeonX = default;
  public static int dungeonY = default;
  public static NSSLC.WorldGeneration.Dust[] dust = System.Array.Empty<NSSLC.WorldGeneration.Dust>();
  public static bool eclipse = default;
  public static bool expertMode = default;
  public static bool fastForwardTimeToDawn = default;
  public static bool fastForwardTimeToDusk = default;
  public static bool forceHalloweenForever = default;
  public static bool forceHalloweenForToday = default;
  public static bool forceXMasForever = default;
  public static bool forceXMasForToday = default;
  public static bool gameMenu = default;
  public static int GameMode = default;
  public static uint GameUpdateCount = default;
  public static bool getGoodWorld = default;
  public static NSSLC.WorldGeneration.Gore[] gore = System.Array.Empty<NSSLC.WorldGeneration.Gore>();
  public static int[] hallowBG = new int[3];
  public static bool halloween = default;
  public static bool hardMode = default;
  public static int hellBackStyle = default;
  public static int helpText = default;
  public static int iceBackStyle = default;
  public static bool infectedSeed = default;
  public static dynamic instance;
  public static int invasionDelay = default;
  public static int invasionSize = default;
  public static int invasionSizeStart = default;
  public static int invasionType = default;
  public static int invasionWarn = default;
  public static double invasionX = default;
  public static bool IsItRaining = default;
  public static bool IsItStorming = default;
  public static bool isThereAWorldSurface = default;
  public static NSSLC.WorldGeneration.WorldItem[] item = System.Array.Empty<NSSLC.WorldGeneration.WorldItem>();
  public static int jungleBackStyle = default;
  public static int[] jungleBG = new int[3];
  public static int ladyBugRainBoost = default;
  public static float leftWorld = default;
  public static Liquid[] liquid;
  public static LiquidBuffer[] liquidBuffer;
  public static dynamic LocalGolfState;
  public static Player LocalPlayer => player[myPlayer];
  public static bool lockMenuBGChange = default;
  public static dynamic Map;
  public static int mapDelay = default;
  public static bool mapReady = default;
  public static int mapTime = default;
  public static bool masterMode = default;
  public static int maxNPCs;
  public static float maxRaining = default;
  public static int maxSectionsX;
  public static int maxSectionsY;
  public static int maxTilesX;
  public static int maxTilesY;
  public static dynamic MaxWorldViewSize;
  public static int menuMode;
  public static dynamic MenuUI;
  public static int moondialCooldown = default;
  public static int moonPhase = default;
  public static int moonType = default;
  public static int[] mushroomBG = new int[3];
  public static int myPlayer;
  public static int netMode = default;
  public static void NewText(params object[] arguments) { }
  public static bool NoFunctionalSurface = default;
  public static void NotifyOfEvent(params object[] arguments) { }
  public static bool noTrapsWorld = default;
  public static bool notTheBeesWorld = default;
  public static NSSLC.WorldGeneration.NPC[] npc = System.Array.Empty<NSSLC.WorldGeneration.NPC>();
  public static int numClouds = default;
  public static int oceanBG = default;
  public static int offLimitBorderTiles = 10;
  public static dynamic ParticleSystem_World_BehindPlayers;
  public static dynamic ParticleSystem_World_OverPlayers;
  public static dynamic Pings;
  public static NSSLC.WorldGeneration.Player[] player = System.Array.Empty<NSSLC.WorldGeneration.Player>();
  public static NSSLC.WorldGeneration.Projectile[] projectile = System.Array.Empty<NSSLC.WorldGeneration.Projectile>();
  public static bool pumpkinMoon = default;
  public static dynamic PylonSystem;
  public static bool raining = default;
  public static int rainTime = default;
  public static NSSLC.WorldGeneration.Utilities.UnifiedRandom rand = new NSSLC.WorldGeneration.Utilities.UnifiedRandom();
  public static bool refreshMap = default;
  public static bool remixWorld = default;
  public static float rightWorld = default;
  public static double rockLayer = default;
  public static dynamic sectionManager;
  public static float shimmerAlpha = default;
  public static float shimmerDarken = default;
  public static Sign[] sign = new Sign[32000];
  public static bool skyblockWorld = default;
  public static bool slimeRain = default;
  public static double slimeRainTime = default;
  public static int slimeWarningTime = default;
  public static int[] snowBG = new int[3];
  public static int[] snowMntBG = new int[2];
  public static int spawnTileX = default;
  public static int spawnTileY = default;
  public static bool starGame = default;
  public static string statusText = default;
  public static int sundialCooldown = default;
  public static bool teamBasedSpawnsSeed = default;
  public static bool tenthAnniversaryWorld = default;
  public static NSSLC.WorldGeneration.Tile[,] tile = new NSSLC.WorldGeneration.Tile[0, 0];
  public static bool[] tileAlch = new bool[TileID.Count];
  public static bool[] tileBlendAll = new bool[TileID.Count];
  public static bool[] tileBrick = new bool[TileID.Count];
  public static bool[] tileCracked = new bool[TileID.Count];
  public static bool[] tileCut = new bool[TileID.Count];
  public static bool[] tileDungeon = new bool[TileID.Count];
  public static bool[] tileFrameImportant = new bool[TileID.Count];
  public static byte[] tileLargeFrames = new byte[TileID.Count];
  public static bool[][] tileMerge = new bool[TileID.Count][];
  public static bool[] tileMergeDirt = new bool[TileID.Count];
  public static bool[] tileMoss = new bool[TileID.Count];
  public static bool[] tileNoAttach = new bool[TileID.Count];
  public static bool[] tilePile = new bool[TileID.Count];
  public static bool[] tileRope = new bool[TileID.Count];
  public static bool[] tileSand = new bool[TileID.Count];
  public static bool[] tileSolid = new bool[TileID.Count];
  public static bool[] tileSolidTop = new bool[TileID.Count];
  public static bool[] tileStone = new bool[TileID.Count];
  public static bool[] tileTable = new bool[TileID.Count];
  public static double time = default;
  public static int[] timeItemSlotCannotBeReusedFor = new int[401];
  public static float topWorld = default;
  public static bool[] townNPCCanSpawn = new bool[NPCID.Count];
  public static int[] treeBGSet1 = new int[3];
  public static int[] treeBGSet2 = new int[3];
  public static int[] treeBGSet3 = new int[3];
  public static int[] treeBGSet4 = new int[3];
  public static int[] treeMntBGSet1 = new int[2];
  public static int[] treeMntBGSet2 = new int[2];
  public static int[] treeMntBGSet3 = new int[2];
  public static int[] treeMntBGSet4 = new int[2];
  public static int[] treeStyle = new int[4];
  public static int[] treeX = new int[4];
  public static int[] underworldBG = new int[5];
  public static int UnderworldLayer = default;
  public static dynamic updateMap;
  public static bool vampireSeed = default;
  public static string versionNumber = default;
  public static bool[] wallDungeon = new bool[WallID.Count];
  public static bool[] wallHouse = new bool[ID.WallID.Count];
  public static int waterStyle = default;
  public static float windSpeedCurrent = default;
  public static float windSpeedTarget = default;
  public static int wofNPCIndex;
  public static dynamic WorldFileMetadata;
  public static string worldPathName = default;
  public static double worldSurface = default;
  public static bool zenithWorld = default;
}
