namespace NSSLC.WorldGeneration.Audio { internal static class NamespaceMarker { } }
namespace NSSLC.WorldGeneration.Chat { internal static class NamespaceMarker { } }
namespace NSSLC.WorldGeneration.DataStructures { internal static class NamespaceMarker { } }
namespace NSSLC.WorldGeneration.Enums { internal static class NamespaceMarker { } }
namespace NSSLC.WorldGeneration.GameContent { internal static class NamespaceMarker { } }
namespace NSSLC.WorldGeneration.GameContent.Achievements { internal static class NamespaceMarker { } }
namespace NSSLC.WorldGeneration.GameContent.Biomes { internal static class NamespaceMarker { } }
namespace NSSLC.WorldGeneration.GameContent.Biomes.CaveHouse { internal static class NamespaceMarker { } }
namespace NSSLC.WorldGeneration.GameContent.Biomes.Desert { internal static class NamespaceMarker { } }
namespace NSSLC.WorldGeneration.GameContent.Creative { internal static class NamespaceMarker { } }
namespace NSSLC.WorldGeneration.GameContent.Events { internal static class NamespaceMarker { } }
namespace NSSLC.WorldGeneration.GameContent.Generation { internal static class NamespaceMarker { } }
namespace NSSLC.WorldGeneration.GameContent.Generation.Dungeon { internal static class NamespaceMarker { } }
namespace NSSLC.WorldGeneration.GameContent.Generation.Dungeon.Entrances { internal static class NamespaceMarker { } }
namespace NSSLC.WorldGeneration.GameContent.Generation.Dungeon.Features { internal static class NamespaceMarker { } }
namespace NSSLC.WorldGeneration.GameContent.Generation.Dungeon.Halls { internal static class NamespaceMarker { } }
namespace NSSLC.WorldGeneration.GameContent.Generation.Dungeon.LayoutProviders { internal static class NamespaceMarker { } }
namespace NSSLC.WorldGeneration.GameContent.Generation.Dungeon.Rooms { internal static class NamespaceMarker { } }
namespace NSSLC.WorldGeneration.GameContent.Prefixes { internal static class NamespaceMarker { } }
namespace NSSLC.WorldGeneration.GameContent.Tile_Entities { internal static class NamespaceMarker { } }
namespace NSSLC.WorldGeneration.GameContent.UI.Elements { internal static class NamespaceMarker { } }
namespace NSSLC.WorldGeneration.GameContent.UI.States { internal static class NamespaceMarker { } }
namespace NSSLC.WorldGeneration.Graphics.Capture { internal static class NamespaceMarker { } }
namespace NSSLC.WorldGeneration.ID { internal static class NamespaceMarker { } }
namespace NSSLC.WorldGeneration.IO { internal static class NamespaceMarker { } }
namespace NSSLC.WorldGeneration.Localization { internal static class NamespaceMarker { } }
namespace NSSLC.WorldGeneration.Map { internal static class NamespaceMarker { } }
namespace NSSLC.WorldGeneration.ObjectData { internal static class NamespaceMarker { } }
namespace NSSLC.WorldGeneration.Testing { internal static class NamespaceMarker { } }
namespace NSSLC.WorldGeneration.UI { internal static class NamespaceMarker { } }
namespace NSSLC.WorldGeneration.Utilities { internal static class NamespaceMarker { } }
namespace NSSLC.WorldGeneration.WorldBuilding { internal static class NamespaceMarker { } }

