using NSSLC.Infrastructure.Network;
using Terraria.Network;
using Terraria.NetWork.Prototype.PacketDesignCompiler.Sample;

namespace NSSLC.NetworkVerification;

internal static class GatewayCapabilitiesVerification {
  public static async Task HostAndPingAsync() {
    ProtocolProfile profile = GatewayVerification.CreateProfile();
    var authority = new RecordingAuthority();
    await using var gateway = new PacketGateway(profile, authority,
        new PacketGatewayOptions { EnableHostAuthorization = true, EnablePing = true });
    GatewayVerification.RegisterProgression(gateway);
    var hostHandled = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);
    gateway.Register(new PacketPolicy(30, NetworkSessionStage.Active, RequiresHost: true),
        new RecordingHandler<Packet30Packet>((context, _, _) => {
          Verify.That(context.IsHost && context.Actor.PlayerSlot == 0,
              "Host-only owner context must come from explicit authority approval.");
          hostHandled.TrySetResult();
          return ValueTask.FromResult(new PacketHandlingResult(true));
        }));
    await using var peer = new GatewayPeer(gateway, profile);
    peer.Receive(new Packet1Packet { Version = "Terraria319" });
    await Verify.EventuallyAsync(() => peer.Session.Stage == NetworkSessionStage.AwaitPlayerData,
        "Host fixture did not enter player data admission.");
    peer.Receive(new Packet161Packet { Payload = new("trusted-host") });
    await Verify.EventuallyAsync(() => peer.Transport.FrameCount == 2,
        "The authority-confirmed host result was not sent.");
    Packet139Packet hostResult = (Packet139Packet)profile.Find(PacketDirection.ServerToClient,
        (byte)139).Decode(peer.Transport.GetFrame(1).AsMemory(3));
    Verify.That(hostResult.Payload.Player == 0 && hostResult.Payload.CountsAsHost,
        "The host result must be generated by the server for the allocated slot.");
    peer.Receive(new Packet6Packet());
    await Verify.EventuallyAsync(() => peer.Session.Stage == NetworkSessionStage.AwaitSectionRequest,
        "Host fixture did not enter section request.");
    peer.Receive(new Packet8Packet());
    await Verify.EventuallyAsync(() => peer.Session.Stage == NetworkSessionStage.Synchronizing,
        "Host fixture did not enter synchronization.");
    peer.Receive(new Packet12Packet());
    await Verify.EventuallyAsync(() => peer.Session.Stage == NetworkSessionStage.Active,
        "Host fixture did not become active.");
    peer.Receive(new Packet30Packet());
    await hostHandled.Task.WaitAsync(TimeSpan.FromSeconds(5));
    peer.Receive(new Packet82Packet { Payload = new(2, new Packet82EmptyModulePayload()) });
    await Verify.EventuallyAsync(() => peer.Transport.FrameCount == 3,
        "Explicitly enabled module Ping did not receive its controlled response.");
    Verify.That(peer.Transport.GetFrame(2)[2] == 82,
        "Enabled Ping must use the module packet response format.");
    Verify.That(GatewayVerification.ReadDiagnostics(gateway).All(item =>
        !item.Code.Contains("trusted-host", StringComparison.Ordinal)),
        "Gateway diagnostics must not include the secret host token.");
  }

  public static async Task SessionCapacityAsync() {
    ProtocolProfile profile = GatewayVerification.CreateProfile();
    await using var gateway = new PacketGateway(profile, new RecordingAuthority(),
        new PacketGatewayOptions { MaximumSessions = 1 });
    await using var peer = new GatewayPeer(gateway, profile);
    var transport = new RecordingTransport();
    await using var other = new PacketConnection(new(Guid.NewGuid(), 1), transport,
        profile, PacketDirection.ClientToServer, ConnectionVerification.Options(),
        new PacketByteBudget(4096));
    PacketProtocolException capacity = Verify.Throws<PacketProtocolException>(
        () => gateway.HandleAsync(other));
    Verify.That(capacity.Code == "ConnectionAdmissionRejected" && gateway.Sessions.Count == 1,
        "Session limits must reject excess connections before allocating another control loop.");
    Verify.Throws<PacketProtocolException>(() => gateway.HandleAsync(peer.Connection));
  }
}
