using NSSLC.Infrastructure.Network;
using Terraria.Network;
using Terraria.NetWork.Prototype.PacketDesignCompiler.Sample;

namespace NSSLC.NetworkVerification;

internal static class GatewayCapabilitiesVerification {
  public static async Task HostAndPingAsync() {
    ProtocolProfile profile = GatewayVerification.CreateProfile();
    var authority = new RecordingAuthority();
    await using var gateway = new PacketGateway(profile, authority,
        new PacketGatewayOptions { EnableHostAuthorization = true, EnablePing = true });
    GatewayVerification.RegisterProgression(gateway);
    var hostHandled = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);
    gateway.Register(new PacketPolicy(30, NetworkSessionStage.Active, RequiresHost: true),
        new RecordingHandler<TogglePVPPacket>((context, _, _) => {
          Verify.That(context.IsHost && context.Actor.PlayerSlot == 0,
              "Host-only owner context must come from explicit authority approval.");
          hostHandled.TrySetResult();
          return ValueTask.FromResult(new PacketHandlingResult(true));
        }));
    await using var peer = new GatewayPeer(gateway, profile);
    peer.Receive(new HelloPacket { Version = "Terraria319" });
    await Verify.EventuallyAsync(() => peer.Session.Stage == NetworkSessionStage.AwaitPlayerData,
        "Host fixture did not enter player data admission.");
    peer.Receive(new HostTokenPacket { HostToken = "trusted-host" });
    await Verify.EventuallyAsync(() => peer.Transport.FrameCount == 2,
        "The authority-confirmed host result was not sent.");
    SetCountsAsHostForGameplayPacket hostResult = (SetCountsAsHostForGameplayPacket)profile.Find(PacketDirection.ServerToClient,
        (byte)139).Decode(peer.Transport.GetFrame(1).AsMemory(3));
    Verify.That(hostResult.Player == 0 && hostResult.CountsAsHost,
        "The host result must be generated by the server for the allocated slot.");
    peer.Receive(new RequestWorldDataPacket());
    await Verify.EventuallyAsync(() => peer.Session.Stage == NetworkSessionStage.AwaitSectionRequest,
        "Host fixture did not enter section request.");
    peer.Receive(new SpawnTileDataPacket());
    await Verify.EventuallyAsync(() => peer.Session.Stage == NetworkSessionStage.Synchronizing,
        "Host fixture did not enter synchronization.");
    peer.Receive(new PlayerSpawnPacket());
    await Verify.EventuallyAsync(() => peer.Session.Stage == NetworkSessionStage.Active,
        "Host fixture did not become active.");
    peer.Receive(new TogglePVPPacket());
    await hostHandled.Task.WaitAsync(TimeSpan.FromSeconds(5));
    var pingPosition = new PacketVector2(125.5f, -42.25f);
    peer.Receive(new NetModulesPacket { ModuleId = 2, Data = new Packet82PingData(pingPosition) });
    await Verify.EventuallyAsync(() => peer.Transport.FrameCount == 3,
        "Explicitly enabled module Ping did not receive its controlled response.");
    byte[] pingFrame = peer.Transport.GetFrame(2);
    var pingReply = (NetModulesPacket)profile.Find(PacketDirection.ServerToClient, (byte)82)
        .Decode(pingFrame.AsMemory(3));
    Verify.That(pingFrame[2] == 82 && pingReply.Data is Packet82PingData data
        && data.Position == pingPosition,
        "Enabled Ping must use the module packet response format.");
    Verify.That(GatewayVerification.ReadDiagnostics(gateway).All(item =>
        !item.Code.Contains("trusted-host", StringComparison.Ordinal)),
        "Gateway diagnostics must not include the secret host token.");
  }

  public static async Task SessionCapacityAsync() {
    ProtocolProfile profile = GatewayVerification.CreateProfile();
    await using var gateway = new PacketGateway(profile, new RecordingAuthority(),
        new PacketGatewayOptions { MaximumSessions = 1 });
    await using var peer = new GatewayPeer(gateway, profile);
    var transport = new RecordingTransport();
    await using var other = new PacketConnection(new(Guid.NewGuid(), 1), transport,
        profile, PacketDirection.ClientToServer, ConnectionVerification.Options(),
        new PacketByteBudget(4096));
    PacketProtocolException capacity = Verify.Throws<PacketProtocolException>(
        () => gateway.HandleAsync(other));
    Verify.That(capacity.Code == "ConnectionAdmissionRejected" && gateway.Sessions.Count == 1,
        "Session limits must reject excess connections before allocating another control loop.");
    Verify.Throws<PacketProtocolException>(() => gateway.HandleAsync(peer.Connection));
  }

  public static async Task LatencyPingAsync() {
    ProtocolProfile profile = GatewayVerification.CreateProfile();
    var authority = new RecordingAuthority();
    await using (var gateway = new PacketGateway(profile, authority,
        new PacketGatewayOptions { EnablePing = true })) {
      GatewayVerification.RegisterProgression(gateway);
      Verify.Throws<ArgumentException>(() => gateway.Register(
          new PacketPolicy(154, NetworkSessionStage.Active),
          new RecordingHandler<PingPacket>((_, _, _) =>
              ValueTask.FromResult(new PacketHandlingResult(true)))));
      await using var peer = new GatewayPeer(gateway, profile);
      await peer.JoinAsync();
      int before = peer.Transport.FrameCount;
      for (int i = 0; i < 5; i++) {
        peer.ReceiveRaw(new byte[] { 3, 0, 154 });
      }
      await Verify.EventuallyAsync(() => peer.Transport.FrameCount == before + 5,
          "Enabled latency Ping must echo every admitted empty packet.");
      for (int i = before; i < before + 5; i++) {
        Verify.That(peer.Transport.GetFrame(i).SequenceEqual(new byte[] { 3, 0, 154 }),
            "The latency response must be exactly the empty packet-154 frame.");
      }
      Verify.That(peer.Session.Stage == NetworkSessionStage.Active,
          "Latency Ping must keep the authenticated session Active.");
      peer.ReceiveRaw(new byte[] { 3, 0, 154 });
      await peer.Run.WaitAsync(TimeSpan.FromSeconds(5));
      Verify.That(GatewayVerification.ReadDiagnostics(gateway).Any(item =>
          item.Code == "RateLimitExceeded" && item.MessageId == 154),
          "Latency Ping must retain its explicit request-rate limit.");
    }
    Verify.That(authority.Releases == 1, "Ping rate rejection must release the actor binding.");

    foreach (bool enabled in new[] { false, true }) {
      await using var gateway = new PacketGateway(profile, new RecordingAuthority(),
          new PacketGatewayOptions { EnablePing = enabled });
      GatewayVerification.RegisterProgression(gateway);
      await using var peer = new GatewayPeer(gateway, profile);
      await peer.JoinAsync();
      int before = peer.Transport.FrameCount;
      peer.ReceiveRaw(enabled ? new byte[] { 4, 0, 154, 0 } : new byte[] { 3, 0, 154 });
      await peer.Run.WaitAsync(TimeSpan.FromSeconds(5));
      Verify.That(peer.Transport.FrameCount == before
          && GatewayVerification.ReadDiagnostics(gateway).Any(item =>
              item.MessageId == 154 && item.Code == (enabled ? "TrailingBytes" : "AdmissionRejected")),
          "Disabled or nonempty latency Ping must fail without producing a reply.");
    }
    await using (var gateway = new PacketGateway(profile, new RecordingAuthority(),
        new PacketGatewayOptions { EnablePing = true })) {
      await using var peer = new GatewayPeer(gateway, profile);
      peer.ReceiveRaw(new byte[] { 3, 0, 154 });
      await peer.Run.WaitAsync(TimeSpan.FromSeconds(5));
      Verify.That(peer.Transport.FrameCount == 0
          && GatewayVerification.ReadDiagnostics(gateway).Any(item =>
              item.Code == "AdmissionRejected" && item.MessageId == 154),
          "Latency Ping must remain unavailable before session admission.");
    }
  }
}
